FROM debian:bookworm-slim

# Instalar dependencias necesarias para dbmazz
RUN apt-get update && apt-get install -y \
    libssl3 \
    ca-certificates \
    libcurl4 \
    && rm -rf /var/lib/apt/lists/*

# Copiar el binario compilado
COPY ../target/release/dbmazz /usr/local/bin/dbmazz
RUN chmod +x /usr/local/bin/dbmazz

# Punto de entrada
ENTRYPOINT ["/usr/local/bin/dbmazz"]



